// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl?: string;
};

export type AvatarStyle = 'gravatar' | 'manual';

/**
 * Request body for creating a comment.
 */
export type CommentCreateBody = {
  /**
   * ID of the post to comment on.
   */
  postId: number;
  /**
   * Comment text.
   */
  text: string;
};

/**
 * A comment under a post.
 */
export type CommentInfo = {
  /**
   * Time the comment was created.
   */
  creationTime?: DateTime;
  /**
   * The comment identifier.
   */
  id?: number;
  /**
   * Time the comment was last edited.
   */
  lastEditTime?: DateTime;
  /**
   * The score (+1/-1 rating) of the comment by the authenticated user.
   */
  ownScore?: Rating;
  /**
   * ID of the post the comment is for.
   */
  postId?: number;
  /**
   * The collective score (+1/-1 rating) of the comment.
   */
  score?: number;
  /**
   * The comment content. The client should render this as Markdown.
   */
  text?: LargeString;
  user?: null | MicroUser;
  /**
   * Resource version. See [versioning](#Versioning) for details.
   */
  version?: DateTime;
};

/**
 * Request body for updating a comment.
 */
export type CommentUpdateBody = {
  /**
   * New comment text.
   */
  text: string;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

/**
 * A RFC 3339 formatted datetime string
 */
export type DateTime = string;

/**
 * Request body for deleting a resource.
 */
export type DeleteBody = {
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

export type ErrorName =
  | 'AddressInUse'
  | 'AddressNotAvailable'
  | 'AlreadyInTransaction'
  | 'ArgumentListTooLong'
  | 'BadConnection'
  | 'BrokenPipe'
  | 'BrokenTransactionManager'
  | 'BytesRejection'
  | 'CheckViolation'
  | 'ClosedConnection'
  | 'CommentNotFound'
  | 'ConnectionAborted'
  | 'ConnectionRefused'
  | 'ConnectionReset'
  | 'ContentTypeMismatch'
  | 'CrossesDevices'
  | 'CryptoError'
  | 'CyclicDependency'
  | 'Deadlock'
  | 'DecodeExhausted'
  | 'DeleteDefault'
  | 'DeserializationError'
  | 'DimensionLimitsExceeded'
  | 'DimensionMismatch'
  | 'DirectoryNotEmpty'
  | 'DuplicatePost'
  | 'EmailAddressInvalidDomain'
  | 'EmailAddressInvalidInput'
  | 'EmailAddressInvalidUser'
  | 'EmailAddressMissingParts'
  | 'EmailAddressUnbalanced'
  | 'EmailCannotParseFilename'
  | 'EmailMissingAt'
  | 'EmailMissingDomain'
  | 'EmailMissingForm'
  | 'EmailMissingLocalPart'
  | 'EmailMissingTo'
  | 'EmailNonAsciiChars'
  | 'EmailTooManyFrom'
  | 'EmptySwf'
  | 'EmptyValue'
  | 'EmptyVideo'
  | 'EnvironmentVariableNotPresent'
  | 'EnvironmentVariableNotUnicode'
  | 'ExecutableFileBusy'
  | 'ExpiredToken'
  | 'ExpressionFailsRegex'
  | 'FailedAlready'
  | 'FailedConnection'
  | 'FailedDecoding'
  | 'FailedEmailTransport'
  | 'FailedEncoding'
  | 'FailedToDeserializeQueryString'
  | 'FFmpegBsfNotFound'
  | 'FFmpegBufferTooSmall'
  | 'FFmpegBug1'
  | 'FFmpegBug2'
  | 'FFmpegDecoderNotFound'
  | 'FFmpegDemuxerNotFound'
  | 'FFmpegEncoderNotFound'
  | 'FFmpegEof'
  | 'FFmpegExit'
  | 'FFmpegExperimental'
  | 'FFmpegExternal'
  | 'FFmpegFilterNotFound'
  | 'FFmpegHttpBadRequest'
  | 'FFmpegHttpForbidden'
  | 'FFmpegHttpNotFound'
  | 'FFmpegHttpOther4xx'
  | 'FFmpegHttpServerError'
  | 'FFmpegHttpUnauthorized'
  | 'FFmpegInputChanged'
  | 'FFmpegInvalidData'
  | 'FFmpegMuxerNotFound'
  | 'FFmpegOptionNotFound'
  | 'FFmpegOutputChanged'
  | 'FFmpegPatchWelcome'
  | 'FFmpegPosixError'
  | 'FFmpegProtocolNotFound'
  | 'FFmpegStreamNotFound'
  | 'FFmpegUnknown'
  | 'FileAlreadyExists'
  | 'FileNotFound'
  | 'FileTooLarge'
  | 'ForeignKeyViolation'
  | 'FromStrError'
  | 'GenericImageError'
  | 'HeaderDeserialization'
  | 'HostUnreachable'
  | 'InsufficientMemory'
  | 'InsufficientPrivileges'
  | 'Interrupted'
  | 'InvalidAuthType'
  | 'InvalidBoundary'
  | 'InvalidByte'
  | 'InvalidCharacter'
  | 'InvalidConnectionUrl'
  | 'InvalidCString'
  | 'InvalidData'
  | 'InvalidDigit'
  | 'InvalidEncoding'
  | 'InvalidExtraData'
  | 'InvalidFilename'
  | 'InvalidFormat'
  | 'InvalidFrameFormat'
  | 'InvalidHeader'
  | 'InvalidInput'
  | 'InvalidLastSymbol'
  | 'InvalidLength'
  | 'InvalidPadding'
  | 'InvalidPassword'
  | 'InvalidPhcStringField'
  | 'InvalidResizeParameters'
  | 'InvalidSort'
  | 'InvalidUploadToken'
  | 'InvalidUserRank'
  | 'InvalidUtf8InPathParam'
  | 'InvalidVersion'
  | 'IsADirectory'
  | 'JsonDataError'
  | 'JsonInvalidData'
  | 'JsonInvalidSyntax'
  | 'JsonIoError'
  | 'JsonSyntaxError'
  | 'JsonUnexpectedEOF'
  | 'MalformedCredentials'
  | 'MalformedToken'
  | 'MalformedValue'
  | 'MissingCodecParameters'
  | 'MissingContent'
  | 'MissingContentType'
  | 'MissingFormData'
  | 'MissingJsonContentType'
  | 'MissingMetadata'
  | 'MissingPathParams'
  | 'MissingSmtpInfo'
  | 'MultipartError'
  | 'NegativeOverflow'
  | 'NetworkDown'
  | 'NetworkUnreachable'
  | 'NoEmail'
  | 'NoMoreData'
  | 'NoNamesGiven'
  | 'NotADirectory'
  | 'NotConnected'
  | 'NotInTransaction'
  | 'NotLoggedIn'
  | 'NotNullViolation'
  | 'NotSeekable'
  | 'OtherIoError'
  | 'OtherPathError'
  | 'OutOfMemory'
  | 'OutOfRange'
  | 'ParamNameDuplicated'
  | 'ParamNameInvalid'
  | 'ParamsMaxExceeded'
  | 'PathDeserializeError'
  | 'PathParseError'
  | 'PathParseErrorAtIndex'
  | 'PathParseErrorAtKey'
  | 'PermissionDenied'
  | 'PhcStringTrailingData'
  | 'PoolCategoryNameAlreadyExists'
  | 'PoolCategoryNotFound'
  | 'PoolNameAlreadyExists'
  | 'PoolNotFound'
  | 'PoolPostAlreadyExists'
  | 'PositiveOverflow'
  | 'PostAlreadyFeatured'
  | 'PostNotFound'
  | 'PostRelationAlreadyExists'
  | 'QueryBuilderError'
  | 'QuotaExceeded'
  | 'ReadExhausted'
  | 'ReadOnlyFilesystem'
  | 'ReadOnlyTransaction'
  | 'RequestError'
  | 'ResourceBusy'
  | 'ResourceHidden'
  | 'ResourceModified'
  | 'RollbackTransaction'
  | 'RowNotFound'
  | 'SelfMerge'
  | 'SerializationError'
  | 'SerializationFailure'
  | 'StaleNetworkFileHandle'
  | 'StorageFull'
  | 'SwfAvm1ParseError'
  | 'SwfInvalidData'
  | 'SwfIoError'
  | 'SwfParseError'
  | 'SwfUnsupported'
  | 'TagCategoryNameAlreadyExists'
  | 'TagCategoryNotFound'
  | 'TagNameAlreadyExists'
  | 'TagNotFound'
  | 'TimedOut'
  | 'TooFewArgs'
  | 'TooManyArgs'
  | 'TooManyLinks'
  | 'UnableToSendCommand'
  | 'UnauthorizedPasswordReset'
  | 'UnexpectedEof'
  | 'UnexpectedOutputSize'
  | 'UnimplementedFrameFormat'
  | 'UninitializedCodec'
  | 'UniqueViolation'
  | 'UnknownArgonError'
  | 'UnknownArgonInvalidValue'
  | 'UnknownDatabaseConnectionError'
  | 'UnknownDatabaseError'
  | 'UnknownEmailAddressError'
  | 'UnknownImageLimitError'
  | 'UnknownImageParameterError'
  | 'UnknownImageUnsupportedError'
  | 'UnknownIntParseError'
  | 'UnknownIoError'
  | 'UnknownJsonRejectionError'
  | 'UnknownMultipartRejectionError'
  | 'UnknownPathDeserializeError'
  | 'UnknownPathRejectionError'
  | 'UnknownQueryError'
  | 'UnknownQueryRejectionError'
  | 'Unsupported'
  | 'UnsupportedAlgorithm'
  | 'UnsupportedCodecHardwareAccelerationDeviceType'
  | 'UnsupportedCodecParameterSets'
  | 'UnsupportedColor'
  | 'UnsupportedExtension'
  | 'UnsupportedFeature'
  | 'UnsupportedFormat'
  | 'UnsupportedImageDimensions'
  | 'UnsupportedPathType'
  | 'UserEmailAlreadyExists'
  | 'UserNameAlreadyExists'
  | 'UsernamePasswordMismatch'
  | 'UsernameTokenMismatch'
  | 'UserNotFound'
  | 'UserTokenNotFound'
  | 'Utf8ConversionError'
  | 'ValueTooLong'
  | 'ValueTooShort'
  | 'WouldBlock'
  | 'WriteRetryLimitReached'
  | 'WriteZero'
  | 'WrongNumberOfPathParameters'
  | 'ZeroNotAllowed';

/**
 * Request body for featuring a post.
 */
export type FeatureBody = {
  /**
   * ID of the post to feature.
   */
  id: number;
};

/**
 * Server information response.
 */
export type InfoResponse = {
  /**
   * Public server configuration.
   */
  config: PublicConfig;
  /**
   * Total disk usage in bytes.
   */
  diskUsage: number;
  featuredPost?: null | PostInfo;
  featuringTime?: null | DateTime;
  featuringUser?: null | SmallString;
  /**
   * Total number of posts on the server.
   */
  postCount: number;
  /**
   * Current server time.
   */
  serverTime: DateTime;
};

export type LargeString = string;

/**
 * Request body for merging resources.
 */
export type MergeBodySmallString = {
  mergeTo: string;
  /**
   * Version of the target resource. See [versioning](#Versioning).
   */
  mergeToVersion: DateTime;
  remove: string;
  /**
   * Version of the source resource. See [versioning](#Versioning).
   */
  removeVersion: DateTime;
};

/**
 * Request body for merging resources.
 */
export type MergeBodyI64 = {
  mergeTo: number;
  /**
   * Version of the target resource. See [versioning](#Versioning).
   */
  mergeToVersion: DateTime;
  remove: number;
  /**
   * Version of the source resource. See [versioning](#Versioning).
   */
  removeVersion: DateTime;
};

/**
 * A pool resource stripped down to `id`, `names`, `category`, `description` and `postCount` fields.
 */
export type MicroPool = {
  /**
   * The name of the category the given pool belongs to.
   */
  category: SmallString;
  /**
   * The pool description (instructions how to use, history etc.). The client should render it as Markdown.
   */
  description: LargeString;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  id: number;
  /**
   * List of pool names (aliases).
   */
  names: Array<SmallString>;
  /**
   * The number of posts the pool has.
   */
  postCount: number;
};

/**
 * A post resource stripped down to `id` and `thumbnailUrl` fields.
 */
export type MicroPost = {
  /**
   * The post identifier.
   */
  id: number;
  /**
   * Where the post thumbnail is located.
   */
  thumbnailUrl: string;
};

/**
 * A tag resource stripped down to `names`, `category` and `usages` fields.
 */
export type MicroTag = {
  /**
   * The name of the category the given tag belongs to.
   */
  category: SmallString;
  /**
   * A list of tag names (aliases). Tagging a post with any name will automatically assign the first name from this list.
   */
  names: Array<SmallString>;
  /**
   * The number of posts the tag was used in.
   */
  usages: number;
};

/**
 * A user resource stripped down to `name` and `avatarUrl` fields.
 */
export type MicroUser = {
  /**
   * The URL to the avatar.
   */
  avatarUrl: string;
  /**
   * The user name.
   */
  name: SmallString;
};

export type MimeType =
  | 'image/bmp'
  | 'image/gif'
  | 'image/jpeg'
  | 'image/png'
  | 'image/webp'
  | 'video/mp4'
  | 'video/quicktime'
  | 'video/webm'
  | 'application/x-shockwave-flash'
  | 'application/vnd.adobe.flash.movie'
  | 'image/avif';

/**
 * Multipart form for file uploads.
 */
export type MultipartUpload = {
  /**
   * Content file (image, video, etc.).
   */
  content?: Blob | File | null;
  /**
   * JSON metadata (same structure as JSON request body).
   */
  metadata: UploadBody;
};

export type MultipartPostCreateBody = {
  /**
   * Content file (image, video, etc.).
   */
  content?: Blob | File | null;
  /**
   * Request body for creating a post.
   */
  metadata: {
    /**
     * If true, the uploader name won't be recorded.
     */
    anonymous?: boolean | null;
    /**
     * Token referencing previously uploaded content.
     */
    contentToken?: string | null;
    /**
     * URL to fetch content from.
     */
    contentUrl?: string | null;
    /**
     * Post description.
     */
    description?: string | null;
    /**
     * Post flags: `loop` or `sound`.
     */
    flags?: Array<PostFlag> | null;
    /**
     * Post annotations.
     */
    notes?: Array<Note> | null;
    /**
     * IDs of related posts.
     */
    relations?: Array<number> | null;
    /**
     * Post safety rating.
     */
    safety: PostSafety;
    /**
     * Source URL or description.
     */
    source?: string | null;
    /**
     * Tags to apply. Non-existent tags will be created automatically.
     */
    tags?: Array<SmallString> | null;
    /**
     * Token referencing previously uploaded thumbnail.
     */
    thumbnailToken?: string | null;
    /**
     * URL to fetch thumbnail from.
     */
    thumbnailUrl?: string | null;
  };
  /**
   * Thumbnail file.
   */
  thumbnail?: Blob | File | null;
};

export type MultipartPostUpdateBody = {
  /**
   * Content file (image, video, etc.).
   */
  content?: Blob | File | null;
  /**
   * Request body for updating a post.
   */
  metadata: {
    /**
     * Token referencing previously uploaded content.
     */
    contentToken?: string | null;
    /**
     * URL to fetch content from.
     */
    contentUrl?: string | null;
    description?: null | LargeString;
    /**
     * Post flags: `loop` or `sound`.
     */
    flags?: Array<PostFlag> | null;
    /**
     * Post annotations.
     */
    notes?: Array<Note> | null;
    /**
     * IDs of related posts.
     */
    relations?: Array<number> | null;
    safety?: null | PostSafety;
    source?: null | LargeString;
    /**
     * Tags to apply. Non-existent tags will be created automatically.
     */
    tags?: Array<SmallString> | null;
    /**
     * Token referencing previously uploaded thumbnail.
     */
    thumbnailToken?: string | null;
    /**
     * URL to fetch thumbnail from.
     */
    thumbnailUrl?: string | null;
    version: DateTime;
  };
  /**
   * Thumbnail file.
   */
  thumbnail?: Blob | File | null;
};

export type MultipartReverseSearchBody = {
  /**
   * Content file (image, video, etc.).
   */
  content?: Blob | File | null;
  /**
   * Request body for reverse image search.
   */
  metadata: {
    /**
     * Token referencing previously uploaded content.
     */
    contentToken?: string | null;
    /**
     * URL to fetch image content from.
     */
    contentUrl?: string | null;
  };
  /**
   * Thumbnail file.
   */
  thumbnail?: Blob | File | null;
};

export type MultipartUserCreateBody = {
  /**
   * Avatar file.
   */
  avatar?: Blob | File | null;
  /**
   * Request body for creating a user.
   */
  metadata: {
    avatarStyle?: null | AvatarStyle;
    /**
     * Token referencing previously uploaded avatar.
     */
    avatarToken?: string | null;
    /**
     * URL to fetch avatar from.
     */
    avatarUrl?: string | null;
    email?: null | SmallString;
    /**
     * Username. Must match `user_name_regex` from server's configuration.
     */
    name: SmallString;
    /**
     * Password. Must match `password_regex` from server's configuration.
     */
    password: SmallString;
    rank?: null | UserRank;
  };
};

export type MultipartUserUpdateBody = {
  /**
   * Avatar file.
   */
  avatar?: Blob | File | null;
  /**
   * Request body for updating a user.
   */
  metadata: {
    avatarStyle?: null | AvatarStyle;
    /**
     * Token referencing previously uploaded avatar.
     */
    avatarToken?: string | null;
    /**
     * URL to fetch avatar from.
     */
    avatarUrl?: string | null;
    email?: null | SmallString;
    name?: null | SmallString;
    password?: null | SmallString;
    rank?: null | UserRank;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version: DateTime;
  };
};

/**
 * Response containing the new temporary password. Sent as plain-text.
 */
export type NewPassword = {
  password: string;
};

export type Note = {
  /**
   * Where to draw the annotation. Each point must have coordinates within 0 to 1.
   * For example, `[[0,0],[0,1],[1,1],[1,0]]` will draw the annotation on the whole post,
   * whereas `[[0,0],[0,0.5],[0.5,0.5],[0.5,0]]` will draw it inside the post's upper left quarter.
   */
  polygon: Array<Array<number>>;
  /**
   * The annotation text. The client should render is as Markdown.
   */
  text: LargeString;
};

/**
 * A result of search operation that involves paging.
 */
export type PagedResponseCommentInfo = {
  /**
   * Number of records on one page.
   */
  limit: number;
  /**
   * The record starting offset, passed in the original request.
   */
  offset: number;
  /**
   * The query passed in the original request that contains a standard [search query](#Search).
   */
  query?: string | null;
  results: Array<{
    /**
     * Time the comment was created.
     */
    creationTime?: DateTime;
    /**
     * The comment identifier.
     */
    id?: number;
    /**
     * Time the comment was last edited.
     */
    lastEditTime?: DateTime;
    /**
     * The score (+1/-1 rating) of the comment by the authenticated user.
     */
    ownScore?: Rating;
    /**
     * ID of the post the comment is for.
     */
    postId?: number;
    /**
     * The collective score (+1/-1 rating) of the comment.
     */
    score?: number;
    /**
     * The comment content. The client should render this as Markdown.
     */
    text?: LargeString;
    user?: null | MicroUser;
    /**
     * Resource version. See [versioning](#Versioning) for details.
     */
    version?: DateTime;
  }>;
  /**
   * How many resources were found. To get the page count, divide this number by `limit`.
   */
  total: number;
};

/**
 * A result of search operation that involves paging.
 */
export type PagedResponsePoolInfo = {
  /**
   * Number of records on one page.
   */
  limit: number;
  /**
   * The record starting offset, passed in the original request.
   */
  offset: number;
  /**
   * The query passed in the original request that contains a standard [search query](#Search).
   */
  query?: string | null;
  results: Array<{
    /**
     * The name of the category the given pool belongs to.
     */
    category?: SmallString;
    /**
     * Time the pool was created.
     */
    creationTime?: DateTime;
    /**
     * The pool description (instructions how to use, history etc.). The client should render it as Markdown.
     */
    description?: LargeString;
    /**
     * The pool identifier.
     */
    id?: number;
    /**
     * Time the pool was last edited.
     */
    lastEditTime?: DateTime;
    /**
     * A list of pool names (aliases).
     */
    names?: Array<SmallString>;
    /**
     * The number of posts the pool has.
     */
    postCount?: number;
    /**
     * An ordered list of posts. Posts are ordered by insertion by default.
     */
    posts?: Array<MicroPost>;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
  /**
   * How many resources were found. To get the page count, divide this number by `limit`.
   */
  total: number;
};

/**
 * A result of search operation that involves paging.
 */
export type PagedResponsePostInfo = {
  /**
   * Number of records on one page.
   */
  limit: number;
  /**
   * The record starting offset, passed in the original request.
   */
  offset: number;
  /**
   * The query passed in the original request that contains a standard [search query](#Search).
   */
  query?: string | null;
  results: Array<{
    /**
     * The original height of the post content.
     */
    canvasHeight?: number;
    /**
     * The original width of the post content.
     */
    canvasWidth?: number;
    /**
     * The BLAKE3 file checksum.
     */
    checksum?: string;
    /**
     * The MD5 file checksum.
     */
    checksumMD5?: string;
    /**
     * How many comments are filed under the post.
     */
    commentCount?: number;
    /**
     * List of comments under the post.
     */
    comments?: Array<CommentInfo>;
    /**
     * Where the post content is located.
     */
    contentUrl?: string;
    /**
     * Time the tag was created.
     */
    creationTime?: DateTime;
    /**
     * Text description for the post. The client should render is as Markdown.
     */
    description?: LargeString;
    /**
     * How many users have the post in their favorites.
     */
    favoriteCount?: number;
    /**
     * List of users that favorited the post.
     */
    favoritedBy?: Array<MicroUser>;
    /**
     * How many times has the post been featured.
     */
    featureCount?: number;
    /**
     * The size of the file in bytes.
     */
    fileSize?: number;
    /**
     * Various flags such as whether the post is looped.
     */
    flags?: PostFlags;
    /**
     * Whether the post uses custom thumbnail.
     */
    hasCustomThumbnail?: boolean;
    /**
     * The post identifier.
     */
    id?: number;
    /**
     * Time the tag was last edited.
     */
    lastEditTime?: DateTime;
    lastFeatureTime?: null | DateTime;
    /**
     * Subsidiary to `<type>`, used to tell exact content format. Useful for `<video>` tags for instance.
     */
    mimeType?: MimeType;
    /**
     * How many notes the post has.
     */
    noteCount?: number;
    /**
     * List of post annotations.
     */
    notes?: Array<Note>;
    /**
     * Whether the authenticated user has given post in their favorites.
     */
    ownFavorite?: boolean;
    /**
     * The score (+1/-1 rating) of the given post by the authenticated user.
     */
    ownScore?: Rating;
    /**
     * List of pools the post is a member of.
     */
    pools?: Array<MicroPool>;
    /**
     * How many posts are related to this post.
     */
    relationCount?: number;
    /**
     * List of related posts. Links to related posts are shown to the user by the web client.
     */
    relations?: Array<MicroPost>;
    /**
     * Whether the post is safe for work.
     */
    safety?: PostSafety;
    /**
     * The collective score (+1/-1 rating) of the given post.
     */
    score?: number;
    /**
     * Where the post was grabbed form, supplied by the user.
     */
    source?: LargeString;
    /**
     * How many tags the post is tagged with.
     */
    tagCount?: number;
    /**
     * List of tags the post is tagged with.
     */
    tags?: Array<MicroTag>;
    /**
     * Where the post thumbnail is located.
     */
    thumbnailUrl?: string;
    /**
     * The type of the post.
     */
    type?: PostType;
    user?: null | MicroUser;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
  /**
   * How many resources were found. To get the page count, divide this number by `limit`.
   */
  total: number;
};

/**
 * A result of search operation that involves paging.
 */
export type PagedResponseSnapshotInfo = {
  /**
   * Number of records on one page.
   */
  limit: number;
  /**
   * The record starting offset, passed in the original request.
   */
  offset: number;
  /**
   * The query passed in the original request that contains a standard [search query](#Search).
   */
  query?: string | null;
  results: Array<{
    data?: unknown;
    id?: SmallString;
    operation?: ResourceOperation;
    time?: DateTime;
    type?: ResourceType;
    user?: null | MicroUser;
  }>;
  /**
   * How many resources were found. To get the page count, divide this number by `limit`.
   */
  total: number;
};

/**
 * A result of search operation that involves paging.
 */
export type PagedResponseTagInfo = {
  /**
   * Number of records on one page.
   */
  limit: number;
  /**
   * The record starting offset, passed in the original request.
   */
  offset: number;
  /**
   * The query passed in the original request that contains a standard [search query](#Search).
   */
  query?: string | null;
  results: Array<{
    /**
     * The name of the category the given tag belongs to.
     */
    category?: SmallString;
    /**
     * Time the tag was created.
     */
    creationTime?: DateTime;
    /**
     * The tag description (instructions how to use, history etc.). The client should render is as Markdown.
     */
    description?: LargeString;
    /**
     * A list of implied tags. Implied tags are automatically appended by the web client on usage.
     */
    implications?: Array<MicroTag>;
    /**
     * Time the tag was last edited.
     */
    lastEditTime?: DateTime;
    /**
     * A list of tag names (aliases). Tagging a post with any name will automatically assign the first name from this list.
     */
    names?: Array<SmallString>;
    /**
     * A list of suggested tags. Suggested tags are shown to the user by the web client on usage.
     */
    suggestions?: Array<MicroTag>;
    /**
     * The number of posts the tag was used in.
     */
    usages?: number;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
  /**
   * How many resources were found. To get the page count, divide this number by `limit`.
   */
  total: number;
};

/**
 * A result of search operation that involves paging.
 */
export type PagedResponseUserInfo = {
  /**
   * Number of records on one page.
   */
  limit: number;
  /**
   * The record starting offset, passed in the original request.
   */
  offset: number;
  /**
   * The query passed in the original request that contains a standard [search query](#Search).
   */
  query?: string | null;
  results: Array<{
    /**
     * How to render the user avatar.
     */
    avatarStyle?: AvatarStyle;
    /**
     * The URL to the avatar.
     */
    avatarUrl?: string;
    /**
     * Number of comments.
     */
    commentCount?: number;
    /**
     * The user registration time.
     */
    creationTime?: DateTime;
    /**
     * Number of disliked posts. It is available only if the request is authenticated by the same user.
     * If it's unavailable, the server returns `false`.
     */
    dislikedPostCount?: PrivateDataI64;
    /**
     * The user email. It is available only if the request is authenticated by the same user,
     * or the authenticated user can change the email. If it's unavailable, the server returns `false`.
     * If the user hasn't specified an email, the server returns `null`.
     */
    email?: PrivateDataOptionSmallString;
    /**
     * Number of favorited posts.
     */
    favoritePostCount?: number;
    /**
     * The last login time.
     */
    lastLoginTime?: DateTime;
    /**
     * Nubmer of liked posts. It is available only if the request is authenticated by the same user.
     * If it's unavailable, the server returns `false`.
     */
    likedPostCount?: PrivateDataI64;
    /**
     * The user name.
     */
    name?: SmallString;
    /**
     * The user rank, which effectively affects their privileges.
     */
    rank?: UserRank;
    /**
     * Number of uploaded posts.
     */
    uploadedPostCount?: number;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
  /**
   * How many resources were found. To get the page count, divide this number by `limit`.
   */
  total: number;
};

/**
 * Request body for creating a pool category.
 */
export type PoolCategoryCreateBody = {
  /**
   * Category color.
   */
  color: SmallString;
  /**
   * Category name. Must match `pool_category_name_regex` from server's configuration.
   */
  name: SmallString;
};

/**
 * A single pool category. The primary purpose of pool categories is to distinguish
 * certain pool types (such as series, relations etc.), which improves user
 * experience.
 */
export type PoolCategoryInfo = {
  /**
   * The category color.
   */
  color?: SmallString;
  /**
   * Whether the pool category is the default one.
   */
  default?: boolean;
  /**
   * The category name.
   */
  name?: SmallString;
  /**
   * How many pools is the given category used with.
   */
  usages?: number;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

/**
 * Request body for updating a pool category.
 */
export type PoolCategoryUpdateBody = {
  color?: null | SmallString;
  name?: null | SmallString;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

/**
 * Request body for creating a pool.
 */
export type PoolCreateBody = {
  /**
   * Category name. Must match an existing pool category.
   */
  category: SmallString;
  description?: null | LargeString;
  /**
   * Pool names. Must match `pool_name_regex` from server's configuration.
   */
  names: Array<SmallString>;
  /**
   * List of post IDs to include in the pool.
   */
  posts?: Array<number> | null;
};

/**
 * An ordered list of posts, with a description and category.
 */
export type PoolInfo = {
  /**
   * The name of the category the given pool belongs to.
   */
  category?: SmallString;
  /**
   * Time the pool was created.
   */
  creationTime?: DateTime;
  /**
   * The pool description (instructions how to use, history etc.). The client should render it as Markdown.
   */
  description?: LargeString;
  /**
   * The pool identifier.
   */
  id?: number;
  /**
   * Time the pool was last edited.
   */
  lastEditTime?: DateTime;
  /**
   * A list of pool names (aliases).
   */
  names?: Array<SmallString>;
  /**
   * The number of posts the pool has.
   */
  postCount?: number;
  /**
   * An ordered list of posts. Posts are ordered by insertion by default.
   */
  posts?: Array<MicroPost>;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

/**
 * Request body for updating a pool.
 */
export type PoolUpdateBody = {
  category?: null | SmallString;
  description?: null | LargeString;
  /**
   * Pool names. Must match `pool_name_regex` from server's configuration.
   */
  names?: Array<SmallString> | null;
  /**
   * List of post IDs. Replaces the previous list.
   */
  posts?: Array<number> | null;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

/**
 * Request body for creating a post.
 */
export type PostCreateBody = {
  /**
   * If true, the uploader name won't be recorded.
   */
  anonymous?: boolean | null;
  /**
   * Token referencing previously uploaded content.
   */
  contentToken?: string | null;
  /**
   * URL to fetch content from.
   */
  contentUrl?: string | null;
  /**
   * Post description.
   */
  description?: string | null;
  /**
   * Post flags: `loop` or `sound`.
   */
  flags?: Array<PostFlag> | null;
  /**
   * Post annotations.
   */
  notes?: Array<Note> | null;
  /**
   * IDs of related posts.
   */
  relations?: Array<number> | null;
  /**
   * Post safety rating.
   */
  safety: PostSafety;
  /**
   * Source URL or description.
   */
  source?: string | null;
  /**
   * Tags to apply. Non-existent tags will be created automatically.
   */
  tags?: Array<SmallString> | null;
  /**
   * Token referencing previously uploaded thumbnail.
   */
  thumbnailToken?: string | null;
  /**
   * URL to fetch thumbnail from.
   */
  thumbnailUrl?: string | null;
};

export type PostFlag = 'loop' | 'sound';

export type PostFlags = Array<PostFlag>;

/**
 * One file together with its metadata posted to the site.
 */
export type PostInfo = {
  /**
   * The original height of the post content.
   */
  canvasHeight?: number;
  /**
   * The original width of the post content.
   */
  canvasWidth?: number;
  /**
   * The BLAKE3 file checksum.
   */
  checksum?: string;
  /**
   * The MD5 file checksum.
   */
  checksumMD5?: string;
  /**
   * How many comments are filed under the post.
   */
  commentCount?: number;
  /**
   * List of comments under the post.
   */
  comments?: Array<CommentInfo>;
  /**
   * Where the post content is located.
   */
  contentUrl?: string;
  /**
   * Time the tag was created.
   */
  creationTime?: DateTime;
  /**
   * Text description for the post. The client should render is as Markdown.
   */
  description?: LargeString;
  /**
   * How many users have the post in their favorites.
   */
  favoriteCount?: number;
  /**
   * List of users that favorited the post.
   */
  favoritedBy?: Array<MicroUser>;
  /**
   * How many times has the post been featured.
   */
  featureCount?: number;
  /**
   * The size of the file in bytes.
   */
  fileSize?: number;
  /**
   * Various flags such as whether the post is looped.
   */
  flags?: PostFlags;
  /**
   * Whether the post uses custom thumbnail.
   */
  hasCustomThumbnail?: boolean;
  /**
   * The post identifier.
   */
  id?: number;
  /**
   * Time the tag was last edited.
   */
  lastEditTime?: DateTime;
  lastFeatureTime?: null | DateTime;
  /**
   * Subsidiary to `<type>`, used to tell exact content format. Useful for `<video>` tags for instance.
   */
  mimeType?: MimeType;
  /**
   * How many notes the post has.
   */
  noteCount?: number;
  /**
   * List of post annotations.
   */
  notes?: Array<Note>;
  /**
   * Whether the authenticated user has given post in their favorites.
   */
  ownFavorite?: boolean;
  /**
   * The score (+1/-1 rating) of the given post by the authenticated user.
   */
  ownScore?: Rating;
  /**
   * List of pools the post is a member of.
   */
  pools?: Array<MicroPool>;
  /**
   * How many posts are related to this post.
   */
  relationCount?: number;
  /**
   * List of related posts. Links to related posts are shown to the user by the web client.
   */
  relations?: Array<MicroPost>;
  /**
   * Whether the post is safe for work.
   */
  safety?: PostSafety;
  /**
   * The collective score (+1/-1 rating) of the given post.
   */
  score?: number;
  /**
   * Where the post was grabbed form, supplied by the user.
   */
  source?: LargeString;
  /**
   * How many tags the post is tagged with.
   */
  tagCount?: number;
  /**
   * List of tags the post is tagged with.
   */
  tags?: Array<MicroTag>;
  /**
   * Where the post thumbnail is located.
   */
  thumbnailUrl?: string;
  /**
   * The type of the post.
   */
  type?: PostType;
  user?: null | MicroUser;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

/**
 * Request body for merging posts.
 */
export type PostMergeBody = {
  mergeTo: number;
  /**
   * Version of the target resource. See [versioning](#Versioning).
   */
  mergeToVersion: DateTime;
  remove: number;
  /**
   * Version of the source resource. See [versioning](#Versioning).
   */
  removeVersion: DateTime;
} & {
  /**
   * If true, replace target post content with source post content.
   */
  replaceContent: boolean;
};

/**
 * Response containing neighboring posts.
 */
export type PostNeighbors = {
  next?: null | PostInfo;
  prev?: null | PostInfo;
};

export type PostSafety = 'safe' | 'sketchy' | 'unsafe';

export type PostType = 'image' | 'animation' | 'video' | 'flash';

/**
 * Request body for updating a post.
 */
export type PostUpdateBody = {
  /**
   * Token referencing previously uploaded content.
   */
  contentToken?: string | null;
  /**
   * URL to fetch content from.
   */
  contentUrl?: string | null;
  description?: null | LargeString;
  /**
   * Post flags: `loop` or `sound`.
   */
  flags?: Array<PostFlag> | null;
  /**
   * Post annotations.
   */
  notes?: Array<Note> | null;
  /**
   * IDs of related posts.
   */
  relations?: Array<number> | null;
  safety?: null | PostSafety;
  source?: null | LargeString;
  /**
   * Tags to apply. Non-existent tags will be created automatically.
   */
  tags?: Array<SmallString> | null;
  /**
   * Token referencing previously uploaded thumbnail.
   */
  thumbnailToken?: string | null;
  /**
   * URL to fetch thumbnail from.
   */
  thumbnailUrl?: string | null;
  version: DateTime;
};

export type PrivateDataOptionSmallString = null | string | boolean;

export type PrivateDataI64 = number | boolean;

export type PrivilegeConfig = {
  comment_create: UserRank;
  comment_delete_any: UserRank;
  comment_delete_own: UserRank;
  comment_edit_any: UserRank;
  comment_edit_own: UserRank;
  comment_list: UserRank;
  comment_score: UserRank;
  comment_view: UserRank;
  pool_category_create: UserRank;
  pool_category_delete: UserRank;
  pool_category_edit_color: UserRank;
  pool_category_edit_name: UserRank;
  pool_category_list: UserRank;
  pool_category_set_default: UserRank;
  pool_category_view: UserRank;
  pool_create: UserRank;
  pool_delete: UserRank;
  pool_edit_category: UserRank;
  pool_edit_description: UserRank;
  pool_edit_name: UserRank;
  pool_edit_post: UserRank;
  pool_list: UserRank;
  pool_merge: UserRank;
  pool_view: UserRank;
  post_bulk_edit_delete: UserRank;
  post_bulk_edit_safety: UserRank;
  post_bulk_edit_tag: UserRank;
  post_create_anonymous: UserRank;
  post_create_identified: UserRank;
  post_delete: UserRank;
  post_edit_content: UserRank;
  post_edit_description: UserRank;
  post_edit_flag: UserRank;
  post_edit_note: UserRank;
  post_edit_relation: UserRank;
  post_edit_safety: UserRank;
  post_edit_source: UserRank;
  post_edit_tag: UserRank;
  post_edit_thumbnail: UserRank;
  post_favorite: UserRank;
  post_feature: UserRank;
  post_list: UserRank;
  post_merge: UserRank;
  post_reverse_search: UserRank;
  post_score: UserRank;
  post_view: UserRank;
  post_view_featured: UserRank;
  snapshot_list: UserRank;
  tag_category_create: UserRank;
  tag_category_delete: UserRank;
  tag_category_edit_color: UserRank;
  tag_category_edit_name: UserRank;
  tag_category_edit_order: UserRank;
  tag_category_list: UserRank;
  tag_category_set_default: UserRank;
  tag_category_view: UserRank;
  tag_create: UserRank;
  tag_delete: UserRank;
  tag_edit_category: UserRank;
  tag_edit_description: UserRank;
  tag_edit_implication: UserRank;
  tag_edit_name: UserRank;
  tag_edit_suggestion: UserRank;
  tag_list: UserRank;
  tag_merge: UserRank;
  tag_view: UserRank;
  upload_create: UserRank;
  upload_use_downloader: UserRank;
  user_create_any: UserRank;
  user_create_self: UserRank;
  user_delete_any: UserRank;
  user_delete_self: UserRank;
  user_edit_any_avatar: UserRank;
  user_edit_any_email: UserRank;
  user_edit_any_name: UserRank;
  user_edit_any_pass: UserRank;
  user_edit_any_rank: UserRank;
  user_edit_self_avatar: UserRank;
  user_edit_self_email: UserRank;
  user_edit_self_name: UserRank;
  user_edit_self_pass: UserRank;
  user_edit_self_rank: UserRank;
  user_list: UserRank;
  user_token_create_any: UserRank;
  user_token_create_self: UserRank;
  user_token_delete_any: UserRank;
  user_token_delete_self: UserRank;
  user_token_edit_any: UserRank;
  user_token_edit_self: UserRank;
  user_token_list_any: UserRank;
  user_token_list_self: UserRank;
  user_view: UserRank;
};

export type PublicConfig = {
  canSendMails?: boolean;
  contactEmail?: null | SmallString;
  defaultUserRank: UserRank;
  enableSafety: boolean;
  name: SmallString;
  passwordRegex: string;
  privileges: PrivilegeConfig;
  tagCategoryNameRegex: string;
  tagNameRegex: string;
  userNameRegex: string;
};

/**
 * Rating value: -1 (dislike), 0 (none), or 1 (like)
 */
export type Rating = number;

/**
 * Request body to apply/change a score.
 */
export type RatingBody = {
  score: Rating;
};

/**
 * Token from password reset email.
 */
export type ResetToken = {
  token: string;
};

export type ResourceOperation = 'created' | 'modified' | 'merged' | 'deleted';

export type ResourceType =
  | 'comment'
  | 'pool'
  | 'pool_category'
  | 'post'
  | 'tag'
  | 'tag_category'
  | 'tag_implication'
  | 'tag_suggestion'
  | 'user'
  | 'user_token';

/**
 * Request body for reverse image search.
 */
export type ReverseSearchBody = {
  /**
   * Token referencing previously uploaded content.
   */
  contentToken?: string | null;
  /**
   * URL to fetch image content from.
   */
  contentUrl?: string | null;
};

/**
 * Response from reverse image search.
 */
export type ReverseSearchResponse = {
  exactPost?: null | PostInfo;
  /**
   * Posts that are visually similar to the input image.
   */
  similarPosts: Array<SimilarPost>;
};

/**
 * A post with its visual similarity distance.
 */
export type SimilarPost = {
  /**
   * Visual similarity distance. Lower is more similar.
   */
  distance: number;
  /**
   * The similar post.
   */
  post: PostInfo;
};

export type SmallString = string;

/**
 * A snapshot is a version of a database resource.
 *
 * **Field meaning**
 *
 * - `<operation>`: what happened to the resource.
 *
 * The value can be either of values below:
 *
 * - `"created"` - the resource has been created
 * - `"modified"` - the resource has been modified
 * - `"deleted"` - the resource has been deleted
 * - `"merged"` - the resource has been merged to another resource
 *
 * - `<resource-type>` and `<resource-id>`: the resource that was changed.
 *
 * The values are correlated as per table below:
 *
 * | `<resource-type>` | `<resource-id>`                  |
 * | ----------------- | -------------------------------  |
 * | `"tag"`           | first tag name at given time     |
 * | `"tag_category"`  | tag category name at given time  |
 * | `"post"`          | post ID                          |
 * | `"pool"`          | pool ID                          |
 * | `"pool_category"` | pool category name at given time |
 *
 * - `<issuer>`: the user who made the change.
 *
 * - `<data>`: the snapshot data, of which content depends on the `<operation>`.
 * More explained later.
 *
 * - `<time>`: when the snapshot was created (i.e. when the resource was changed),
 * formatted as per RFC 3339.
 *
 * **`<data>` field for creation snapshots**
 *
 * The value can be either of structures below, depending on
 * `<resource-type>`:
 *
 * - Tag category snapshot data (`<resource-type> = "tag_category"`)
 *
 * *Example*
 *
 * ```json5
 * {
 * "name":  "character",
 * "color": "#FF0000",
 * "default": false
 * }
 * ```
 *
 * - Tag snapshot data (`<resource-type> = "tag"`)
 *
 * *Example*
 *
 * ```json5
 * {
 * "names":        ["tag1", "tag2", "tag3"],
 * "category":     "plain",
 * "implications": ["imp1", "imp2", "imp3"],
 * "suggestions":  ["sug1", "sug2", "sug3"]
 * }
 * ```
 *
 * - Post snapshot data (`<resource-type> = "post"`)
 *
 * *Example*
 *
 * ```json5
 * {
 * "source": "http://example.com/",
 * "safety": "safe",
 * "checksum": "deadbeef",
 * "tags": ["tag1", "tag2"],
 * "relations": [1, 2],
 * "notes": [<note1>, <note2>, <note3>],
 * "flags": ["loop"],
 * "featured": false
 * }
 * ```
 *
 * - Pool category snapshot data (`<resource-type> = "pool_category"`)
 *
 * *Example*
 *
 * ```json5
 * {
 * "name":  "collection",
 * "color": "#00FF00",
 * "default": false
 * }
 * ```
 *
 * - Pool snapshot data (`<resource-type> = "pool"`)
 *
 * *Example*
 *
 * ```json5
 * {
 * "names":    ["primes", "primed", "primey"],
 * "category": "mathematical",
 * "posts":    [2, 3, 5, 7, 11, 13, 17]
 * }
 * ```
 *
 *
 * **`<data>` field for modification snapshots**
 *
 * The value is a property-wise recursive diff between previous version of the
 * resource and its current version. Its structure is a `<dictionary-diff>` of
 * dictionaries as created by creation snapshots, which is described below.
 *
 * `<primitive>`: any primitive (number or a string)
 *
 * `<anything>`: any dictionary, list or primitive
 *
 * `<dictionary-diff>`:
 *
 * ```json5
 * {
 * "type": "object change",
 * "value":
 * {
 * "property-of-any-type-1":
 * {
 * "type": "deleted property",
 * "value": <anything>
 * },
 * "property-of-any-type-2":
 * {
 * "type": "added property",
 * "value": <anything>
 * },
 * "primitive-property":
 * {
 * "type": "primitive change",
 * "old-value": "<primitive>",
 * "new-value": "<primitive>"
 * },
 * "list-property": <list-diff>,
 * "dictionary-property": <dictionary-diff>
 * }
 * }
 * ```
 *
 * `<list-diff>`:
 *
 * ```json5
 * {
 * "type": "list change",
 * "removed": [<anything>, <anything>],
 * "added": [<anything>, <anything>]
 * }
 * ```
 *
 * Example - a diff for a post that has changed source and has one note added.
 * Note the similarities with the structure of post creation snapshots.
 *
 * ```json5
 * {
 * "type": "object change",
 * "value":
 * {
 * "source":
 * {
 * "type": "primitive change",
 * "old-value": None,
 * "new-value": "new source"
 * },
 * "notes":
 * {
 * "type": "list change",
 * "removed": [],
 * "added":
 * [
 * {"polygon": [[0, 0], [0, 1], [1, 1]], "text": "new note"}
 * ]
 * }
 * }
 * }
 * ```
 *
 * Since the snapshot dictionaries structure is pretty immutable, you probably
 * won't see `added property` or `deleted property` around. This observation holds
 * true even if the way the snapshots are generated changes - szurubooru stores
 * just the diffs rather than original snapshots, so it wouldn't be able to
 * generate a diff against an old version.
 *
 * **`<data>` field for deletion snapshots**
 *
 * Same as creation snapshot. In emergencies, it can be used to reconstruct
 * deleted entities. Please note that this does not constitute as means against
 * vandalism (it's still possible to cause chaos by mass editing - this should be
 * dealt with by configuring role privileges in the config) or replace database
 * backups.
 *
 * **`<data>` field for merge snapshots**
 *
 * A tuple containing 2 elements:
 *
 * - resource type equivalent to `<resource-type>` of the target entity.
 * - resource ID equivalent to `<resource-id>` of the target entity.
 */
export type SnapshotInfo = {
  data?: unknown;
  id?: SmallString;
  operation?: ResourceOperation;
  time?: DateTime;
  type?: ResourceType;
  user?: null | MicroUser;
};

/**
 * Request body for creating a tag category.
 */
export type TagCategoryCreateBody = {
  /**
   * Category color.
   */
  color: SmallString;
  /**
   * Category name. Must match `tag_category_name_regex` from server's configuration.
   */
  name: SmallString;
  /**
   * Display order for the category.
   */
  order: number;
};

/**
 * A single tag category. The primary purpose of tag categories is to distinguish
 * certain tag types (such as characters, media type etc.), which improves user
 * experience.
 */
export type TagCategoryInfo = {
  /**
   * The category color.
   */
  color?: SmallString;
  /**
   * Whether the tag category is the default one.
   */
  default?: boolean;
  /**
   * The category name.
   */
  name?: SmallString;
  /**
   * The order in which tags with this category are displayed, ascending.
   */
  order?: number;
  /**
   * How many tags is the given category used with.
   */
  usages?: number;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

/**
 * Request body for updating a tag category.
 */
export type TagCategoryUpdateBody = {
  color?: null | SmallString;
  name?: null | SmallString;
  /**
   * Display order for the category.
   */
  order?: number | null;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

/**
 * Request body for creating a tag.
 */
export type TagCreateBody = {
  /**
   * Category name. Must match an existing tag category.
   */
  category: SmallString;
  description?: null | LargeString;
  /**
   * Implied tags. Non-existent tags will be created automatically.
   */
  implications?: Array<SmallString> | null;
  /**
   * Tag names. Must match `tag_name_regex` from server's configuration.
   */
  names: Array<SmallString>;
  /**
   * Suggested tags. Non-existent tags will be created automatically.
   */
  suggestions?: Array<SmallString> | null;
};

/**
 * A single tag. Tags are used to let users search for posts.
 */
export type TagInfo = {
  /**
   * The name of the category the given tag belongs to.
   */
  category?: SmallString;
  /**
   * Time the tag was created.
   */
  creationTime?: DateTime;
  /**
   * The tag description (instructions how to use, history etc.). The client should render is as Markdown.
   */
  description?: LargeString;
  /**
   * A list of implied tags. Implied tags are automatically appended by the web client on usage.
   */
  implications?: Array<MicroTag>;
  /**
   * Time the tag was last edited.
   */
  lastEditTime?: DateTime;
  /**
   * A list of tag names (aliases). Tagging a post with any name will automatically assign the first name from this list.
   */
  names?: Array<SmallString>;
  /**
   * A list of suggested tags. Suggested tags are shown to the user by the web client on usage.
   */
  suggestions?: Array<MicroTag>;
  /**
   * The number of posts the tag was used in.
   */
  usages?: number;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

/**
 * A sibling tag with its co-occurrence count.
 */
export type TagSibling = {
  /**
   * Number of times this tag appears with the queried tag.
   */
  occurrences: number;
  /**
   * The sibling tag.
   */
  tag: TagInfo;
};

/**
 * Response containing tag siblings.
 */
export type TagSiblings = {
  /**
   * List of sibling tags sorted by occurrence count.
   */
  results: Array<TagSibling>;
};

/**
 * Request body for updating a tag.
 */
export type TagUpdateBody = {
  category?: null | SmallString;
  description?: null | LargeString;
  /**
   * Implied tags. Non-existent tags will be created automatically.
   */
  implications?: Array<SmallString> | null;
  /**
   * Tag names. Must match `tag_name_regex` from server's configuration.
   */
  names?: Array<SmallString> | null;
  /**
   * Suggested tags. Non-existent tags will be created automatically.
   */
  suggestions?: Array<SmallString> | null;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

/**
 * A result of search operation that doesn't involve paging.
 */
export type UnpagedResponsePoolCategoryInfo = {
  results: Array<{
    /**
     * The category color.
     */
    color?: SmallString;
    /**
     * Whether the pool category is the default one.
     */
    default?: boolean;
    /**
     * The category name.
     */
    name?: SmallString;
    /**
     * How many pools is the given category used with.
     */
    usages?: number;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
};

/**
 * A result of search operation that doesn't involve paging.
 */
export type UnpagedResponseTagCategoryInfo = {
  results: Array<{
    /**
     * The category color.
     */
    color?: SmallString;
    /**
     * Whether the tag category is the default one.
     */
    default?: boolean;
    /**
     * The category name.
     */
    name?: SmallString;
    /**
     * The order in which tags with this category are displayed, ascending.
     */
    order?: number;
    /**
     * How many tags is the given category used with.
     */
    usages?: number;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
};

/**
 * A result of search operation that doesn't involve paging.
 */
export type UnpagedResponseUserTokenInfo = {
  results: Array<{
    /**
     * Time the user token was created.
     */
    creationTime?: DateTime;
    /**
     * Whether the token is still valid for authentication.
     */
    enabled?: boolean;
    expirationTime?: null | DateTime;
    /**
     * Time the user token was last edited.
     */
    lastEditTime?: DateTime;
    /**
     * The last time this token was used during a login involving `?bump-login`.
     */
    lastUsageTime?: DateTime;
    /**
     * A note that describes the token.
     */
    note?: LargeString;
    /**
     * The token that can be used to authenticate the user.
     */
    token?: string;
    /**
     * The user that owns the token.
     */
    user?: MicroUser;
    /**
     * Resource version. See [versioning](#Versioning).
     */
    version?: DateTime;
  }>;
};

/**
 * Request body for uploading a temporary file.
 */
export type UploadBody = {
  /**
   * URL to fetch content from.
   */
  contentUrl: string;
};

/**
 * Response containing the upload token.
 */
export type UploadResponse = {
  /**
   * Token to reference this upload in other requests.
   */
  token: string;
};

/**
 * Request body for creating a user.
 */
export type UserCreateBody = {
  avatarStyle?: null | AvatarStyle;
  /**
   * Token referencing previously uploaded avatar.
   */
  avatarToken?: string | null;
  /**
   * URL to fetch avatar from.
   */
  avatarUrl?: string | null;
  email?: null | SmallString;
  /**
   * Username. Must match `user_name_regex` from server's configuration.
   */
  name: SmallString;
  /**
   * Password. Must match `password_regex` from server's configuration.
   */
  password: SmallString;
  rank?: null | UserRank;
};

/**
 * A single user.
 */
export type UserInfo = {
  /**
   * How to render the user avatar.
   */
  avatarStyle?: AvatarStyle;
  /**
   * The URL to the avatar.
   */
  avatarUrl?: string;
  /**
   * Number of comments.
   */
  commentCount?: number;
  /**
   * The user registration time.
   */
  creationTime?: DateTime;
  /**
   * Number of disliked posts. It is available only if the request is authenticated by the same user.
   * If it's unavailable, the server returns `false`.
   */
  dislikedPostCount?: PrivateDataI64;
  /**
   * The user email. It is available only if the request is authenticated by the same user,
   * or the authenticated user can change the email. If it's unavailable, the server returns `false`.
   * If the user hasn't specified an email, the server returns `null`.
   */
  email?: PrivateDataOptionSmallString;
  /**
   * Number of favorited posts.
   */
  favoritePostCount?: number;
  /**
   * The last login time.
   */
  lastLoginTime?: DateTime;
  /**
   * Nubmer of liked posts. It is available only if the request is authenticated by the same user.
   * If it's unavailable, the server returns `false`.
   */
  likedPostCount?: PrivateDataI64;
  /**
   * The user name.
   */
  name?: SmallString;
  /**
   * The user rank, which effectively affects their privileges.
   */
  rank?: UserRank;
  /**
   * Number of uploaded posts.
   */
  uploadedPostCount?: number;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

export type UserRank =
  | 'anonymous'
  | 'restricted'
  | 'regular'
  | 'power'
  | 'moderator'
  | 'administrator';

/**
 * Request body for creating a user token.
 */
export type UserTokenCreateBody = {
  /**
   * Whether the token is enabled. Defaults to `true` if not present.
   */
  enabled?: boolean | null;
  expirationTime?: null | DateTime;
  /**
   * Optional note describing the token's purpose.
   */
  note?: string | null;
};

/**
 * A single user token.
 */
export type UserTokenInfo = {
  /**
   * Time the user token was created.
   */
  creationTime?: DateTime;
  /**
   * Whether the token is still valid for authentication.
   */
  enabled?: boolean;
  expirationTime?: null | DateTime;
  /**
   * Time the user token was last edited.
   */
  lastEditTime?: DateTime;
  /**
   * The last time this token was used during a login involving `?bump-login`.
   */
  lastUsageTime?: DateTime;
  /**
   * A note that describes the token.
   */
  note?: LargeString;
  /**
   * The token that can be used to authenticate the user.
   */
  token?: string;
  /**
   * The user that owns the token.
   */
  user?: MicroUser;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version?: DateTime;
};

/**
 * Request body for updating a user token.
 */
export type UserTokenUpdateBody = {
  /**
   * Whether the token is enabled.
   */
  enabled?: boolean | null;
  expirationTime?: null | DateTime;
  note?: null | LargeString;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

/**
 * Request body for updating a user.
 */
export type UserUpdateBody = {
  avatarStyle?: null | AvatarStyle;
  /**
   * Token referencing previously uploaded avatar.
   */
  avatarToken?: string | null;
  /**
   * URL to fetch avatar from.
   */
  avatarUrl?: string | null;
  email?: null | SmallString;
  name?: null | SmallString;
  password?: null | SmallString;
  rank?: null | UserRank;
  /**
   * Resource version. See [versioning](#Versioning).
   */
  version: DateTime;
};

export type DeleteData = {
  body: DeleteBody;
  path: {
    /**
     * Comment ID
     */
    id: number;
  };
  query?: never;
  url: '/comment/{id}';
};

export type DeleteErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Comment does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type DeleteResponses = {
  200: unknown;
};

export type GetData = {
  body?: never;
  path: {
    /**
     * Comment ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/comment/{id}';
};

export type GetErrors = {
  /**
   * Comment is hidden
   */
  403: unknown;
  /**
   * Comment does not exist
   */
  404: unknown;
};

export type GetResponses = {
  200: CommentInfo;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type UpdateData = {
  body: CommentUpdateBody;
  path: {
    /**
     * Comment ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/comment/{id}';
};

export type UpdateErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Comment does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type UpdateResponses = {
  200: CommentInfo;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type RateData = {
  body: RatingBody;
  path: {
    /**
     * Comment ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/comment/{id}/score';
};

export type RateErrors = {
  /**
   * Score is invalid
   */
  400: unknown;
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Comment does not exist
   */
  404: unknown;
};

export type RateResponses = {
  200: CommentInfo;
};

export type RateResponse = RateResponses[keyof RateResponses];

export type ListData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
    /**
     * Starting position in the result set
     */
    offset?: number | null;
    /**
     * Maximum number of results to return
     */
    limit: number;
  };
  url: '/comments';
};

export type ListErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type ListResponses = {
  200: PagedResponseCommentInfo;
};

export type ListResponse = ListResponses[keyof ListResponses];

export type CreateData = {
  body: CommentCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/comments';
};

export type CreateErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
};

export type CreateResponses = {
  200: CommentInfo;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type GetFeaturedData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/featured-post';
};

export type GetFeaturedErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type GetFeaturedResponses = {
  200: null | PostInfo;
};

export type GetFeaturedResponse = GetFeaturedResponses[keyof GetFeaturedResponses];

export type FeatureData = {
  body: FeatureBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/featured-post';
};

export type FeatureErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Trying to feature a post that is currently featured
   */
  409: unknown;
};

export type FeatureResponses = {
  200: PostInfo;
};

export type FeatureResponse = FeatureResponses[keyof FeatureResponses];

export type Get2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/info';
};

export type Get2Responses = {
  200: InfoResponse;
};

export type Get2Response = Get2Responses[keyof Get2Responses];

export type RequestResetData = {
  body?: never;
  path: {
    /**
     * User email or username
     */
    identifier: SmallString;
  };
  query?: never;
  url: '/password-reset/{identifier}';
};

export type RequestResetErrors = {
  /**
   * User does not exist
   */
  404: unknown;
  /**
   * User hasn't provided an email address
   */
  422: unknown;
};

export type RequestResetResponses = {
  /**
   * Password reset email sent
   */
  200: unknown;
};

export type ResetPasswordData = {
  body: ResetToken;
  path: {
    /**
     * User email or username
     */
    identifier: string;
  };
  query?: never;
  url: '/password-reset/{identifier}';
};

export type ResetPasswordErrors = {
  /**
   * Token is missing or invalid
   */
  400: unknown;
  /**
   * User does not exist
   */
  404: unknown;
};

export type ResetPasswordResponses = {
  /**
   * New password generated
   */
  200: NewPassword;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type Create2Data = {
  body: PoolCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool';
};

export type Create2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * At least one post ID does not exist
   */
  404: unknown;
  /**
   * There is at least one duplicate post
   */
  409: unknown;
  /**
   * Category is missing or invalid
   */
  422: unknown;
};

export type Create2Responses = {
  200: PoolInfo;
};

export type Create2Response = Create2Responses[keyof Create2Responses];

export type List2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool-categories';
};

export type List2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List2Responses = {
  200: UnpagedResponsePoolCategoryInfo;
};

export type List2Response = List2Responses[keyof List2Responses];

export type Create3Data = {
  body: PoolCategoryCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool-categories';
};

export type Create3Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Name is used by an existing pool category
   */
  409: unknown;
  /**
   * Color is invalid or missing
   */
  422: unknown;
};

export type Create3Responses = {
  200: PoolCategoryInfo;
};

export type Create3Response = Create3Responses[keyof Create3Responses];

export type Delete2Data = {
  body: DeleteBody;
  path: {
    /**
     * Pool category name
     */
    name: string;
  };
  query?: never;
  url: '/pool-category/{name}';
};

export type Delete2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Pool category does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
  /**
   * Pool category is the default category
   */
  422: unknown;
};

export type Delete2Responses = {
  200: unknown;
};

export type Get3Data = {
  body?: never;
  path: {
    /**
     * Pool category name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool-category/{name}';
};

export type Get3Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Pool category does not exist
   */
  404: unknown;
};

export type Get3Responses = {
  200: PoolCategoryInfo;
};

export type Get3Response = Get3Responses[keyof Get3Responses];

export type Update2Data = {
  body: PoolCategoryUpdateBody;
  path: {
    /**
     * Pool category name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool-category/{name}';
};

export type Update2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Pool category does not exist
   */
  404: unknown;
  /**
   * Name is used by an existing pool category
   */
  409: unknown;
  /**
   * Color is invalid
   */
  422: unknown;
};

export type Update2Responses = {
  200: PoolCategoryInfo;
};

export type Update2Response = Update2Responses[keyof Update2Responses];

export type SetDefaultData = {
  body?: never;
  path: {
    /**
     * Pool category name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool-category/{name}/default';
};

export type SetDefaultErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Pool category does not exist
   */
  404: unknown;
};

export type SetDefaultResponses = {
  200: PoolCategoryInfo;
};

export type SetDefaultResponse = SetDefaultResponses[keyof SetDefaultResponses];

export type MergeData = {
  body: MergeBodyI64;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool-merge';
};

export type MergeErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Source or target pool does not exist
   */
  404: unknown;
  /**
   * Version of either pool is outdated
   */
  409: unknown;
  /**
   * Source pool is the same as the target pool
   */
  422: unknown;
};

export type MergeResponses = {
  200: PoolInfo;
};

export type MergeResponse = MergeResponses[keyof MergeResponses];

export type Delete3Data = {
  body: DeleteBody;
  path: {
    /**
     * Pool ID
     */
    id: number;
  };
  query?: never;
  url: '/pool/{id}';
};

export type Delete3Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Pool does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type Delete3Responses = {
  200: unknown;
};

export type Get4Data = {
  body?: never;
  path: {
    /**
     * Pool ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool/{id}';
};

export type Get4Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Pool does not exist
   */
  404: unknown;
};

export type Get4Responses = {
  200: PoolInfo;
};

export type Get4Response = Get4Responses[keyof Get4Responses];

export type Update3Data = {
  body: PoolUpdateBody;
  path: {
    /**
     * Pool ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/pool/{id}';
};

export type Update3Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * At least one post ID does not exist
   */
  404: unknown;
  /**
   * There is at least one duplicate post
   */
  409: unknown;
  /**
   * Category is invalid
   */
  422: unknown;
};

export type Update3Responses = {
  200: PoolInfo;
};

export type Update3Response = Update3Responses[keyof Update3Responses];

export type List3Data = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
    /**
     * Starting position in the result set
     */
    offset?: number | null;
    /**
     * Maximum number of results to return
     */
    limit: number;
  };
  url: '/pools';
};

export type List3Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List3Responses = {
  200: PagedResponsePoolInfo;
};

export type List3Response = List3Responses[keyof List3Responses];

export type Merge2Data = {
  body: PostMergeBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post-merge';
};

export type Merge2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Source or target post does not exist
   */
  404: unknown;
  /**
   * Version of either post is outdated
   */
  409: unknown;
  /**
   * Source post is the same as the target post
   */
  422: unknown;
};

export type Merge2Responses = {
  200: PostInfo;
};

export type Merge2Response = Merge2Responses[keyof Merge2Responses];

export type Delete4Data = {
  body: DeleteBody;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: never;
  url: '/post/{id}';
};

export type Delete4Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type Delete4Responses = {
  200: {
    [key: string]: unknown;
  };
};

export type Delete4Response = Delete4Responses[keyof Delete4Responses];

export type Get5Data = {
  body?: never;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post/{id}';
};

export type Get5Errors = {
  /**
   * Post is hidden
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
};

export type Get5Responses = {
  200: PostInfo;
};

export type Get5Response = Get5Responses[keyof Get5Responses];

export type Update4Data = {
  body: PostUpdateBody;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post/{id}';
};

export type Update4Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Relations refer to non-existing posts
   */
  404: unknown;
  /**
   * Post content already exists
   */
  409: unknown;
  /**
   * Flags are invalid
   */
  422: unknown;
};

export type Update4Responses = {
  200: PostInfo;
};

export type Update4Response = Update4Responses[keyof Update4Responses];

export type GetNeighborsData = {
  body?: never;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post/{id}/around';
};

export type GetNeighborsErrors = {
  /**
   * Post is hidden
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
};

export type GetNeighborsResponses = {
  200: PostNeighbors;
};

export type GetNeighborsResponse = GetNeighborsResponses[keyof GetNeighborsResponses];

export type UnfavoriteData = {
  body?: never;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post/{id}/favorite';
};

export type UnfavoriteErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
};

export type UnfavoriteResponses = {
  200: PostInfo;
};

export type UnfavoriteResponse = UnfavoriteResponses[keyof UnfavoriteResponses];

export type FavoriteData = {
  body?: never;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post/{id}/favorite';
};

export type FavoriteErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
};

export type FavoriteResponses = {
  200: PostInfo;
};

export type FavoriteResponse = FavoriteResponses[keyof FavoriteResponses];

export type Rate2Data = {
  body: RatingBody;
  path: {
    /**
     * Post ID
     */
    id: number;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/post/{id}/score';
};

export type Rate2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Post does not exist
   */
  404: unknown;
  /**
   * Score is invalid
   */
  422: unknown;
};

export type Rate2Responses = {
  200: PostInfo;
};

export type Rate2Response = Rate2Responses[keyof Rate2Responses];

export type List4Data = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
    /**
     * Starting position in the result set
     */
    offset?: number | null;
    /**
     * Maximum number of results to return
     */
    limit: number;
  };
  url: '/posts';
};

export type List4Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List4Responses = {
  200: PagedResponsePostInfo;
};

export type List4Response = List4Responses[keyof List4Responses];

export type Create4Data = {
  body: PostCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/posts';
};

export type Create4Errors = {
  /**
   * Post content is missing
   */
  400: unknown;
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Relations refer to non-existing posts
   */
  404: unknown;
  /**
   * Post content already exists
   */
  409: unknown;
  /**
   * Flags are invalid
   */
  422: unknown;
};

export type Create4Responses = {
  200: PostInfo;
};

export type Create4Response = Create4Responses[keyof Create4Responses];

export type ReverseSearchData = {
  body: ReverseSearchBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/posts/reverse-search';
};

export type ReverseSearchErrors = {
  /**
   * Reverse search content is missing
   */
  400: unknown;
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type ReverseSearchResponses = {
  200: ReverseSearchResponse;
};

export type ReverseSearchResponse2 = ReverseSearchResponses[keyof ReverseSearchResponses];

export type List5Data = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
    /**
     * Starting position in the result set
     */
    offset?: number | null;
    /**
     * Maximum number of results to return
     */
    limit: number;
  };
  url: '/snapshots';
};

export type List5Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List5Responses = {
  200: PagedResponseSnapshotInfo;
};

export type List5Response = List5Responses[keyof List5Responses];

export type List6Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-categories';
};

export type List6Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List6Responses = {
  200: UnpagedResponseTagCategoryInfo;
};

export type List6Response = List6Responses[keyof List6Responses];

export type Create5Data = {
  body: TagCategoryCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-categories';
};

export type Create5Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Name is used by an existing tag category
   */
  409: unknown;
  /**
   * Color is invalid or missing
   */
  422: unknown;
};

export type Create5Responses = {
  200: TagCategoryInfo;
};

export type Create5Response = Create5Responses[keyof Create5Responses];

export type Delete5Data = {
  body: DeleteBody;
  path: {
    /**
     * Tag category name
     */
    name: string;
  };
  query?: never;
  url: '/tag-category/{name}';
};

export type Delete5Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Tag category does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
  /**
   * Tag category is the default category
   */
  422: unknown;
};

export type Delete5Responses = {
  200: {
    [key: string]: unknown;
  };
};

export type Delete5Response = Delete5Responses[keyof Delete5Responses];

export type Get6Data = {
  body?: never;
  path: {
    /**
     * Tag category name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-category/{name}';
};

export type Get6Errors = {
  /**
   * Tag category is hidden
   */
  403: unknown;
  /**
   * Tag category does not exist
   */
  404: unknown;
};

export type Get6Responses = {
  200: TagCategoryInfo;
};

export type Get6Response = Get6Responses[keyof Get6Responses];

export type Update5Data = {
  body: TagCategoryUpdateBody;
  path: {
    /**
     * Tag category name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-category/{name}';
};

export type Update5Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Tag category does not exist
   */
  404: unknown;
  /**
   * Name is used by an existing tag category
   */
  409: unknown;
  /**
   * Color is invalid
   */
  422: unknown;
};

export type Update5Responses = {
  200: TagCategoryInfo;
};

export type Update5Response = Update5Responses[keyof Update5Responses];

export type SetDefault2Data = {
  body: {
    [key: string]: unknown;
  };
  path: {
    /**
     * Tag category name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-category/{name}/default';
};

export type SetDefault2Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Tag category does not exist
   */
  404: unknown;
};

export type SetDefault2Responses = {
  200: TagCategoryInfo;
};

export type SetDefault2Response = SetDefault2Responses[keyof SetDefault2Responses];

export type Merge3Data = {
  body: MergeBodySmallString;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-merge';
};

export type Merge3Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Source or target tag does not exist
   */
  404: unknown;
  /**
   * Version of either tag is outdated
   */
  409: unknown;
  /**
   * Source tag is the same as the target tag
   */
  422: unknown;
};

export type Merge3Responses = {
  200: TagInfo;
};

export type Merge3Response = Merge3Responses[keyof Merge3Responses];

export type GetSiblingsData = {
  body?: never;
  path: {
    /**
     * Tag name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag-siblings/{name}';
};

export type GetSiblingsErrors = {
  /**
   * Tag is hidden
   */
  403: unknown;
  /**
   * Tag does not exist
   */
  404: unknown;
};

export type GetSiblingsResponses = {
  200: TagSiblings;
};

export type GetSiblingsResponse = GetSiblingsResponses[keyof GetSiblingsResponses];

export type Delete6Data = {
  body: DeleteBody;
  path: {
    /**
     * Tag name
     */
    name: string;
  };
  query?: never;
  url: '/tag/{name}';
};

export type Delete6Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Tag does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type Delete6Responses = {
  200: {
    [key: string]: unknown;
  };
};

export type Delete6Response = Delete6Responses[keyof Delete6Responses];

export type Get7Data = {
  body?: never;
  path: {
    /**
     * Tag name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag/{name}';
};

export type Get7Errors = {
  /**
   * Tag is hidden
   */
  403: unknown;
  /**
   * Tag does not exist
   */
  404: unknown;
};

export type Get7Responses = {
  200: TagInfo;
};

export type Get7Response = Get7Responses[keyof Get7Responses];

export type Update6Data = {
  body: TagUpdateBody;
  path: {
    /**
     * Tag name
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tag/{name}';
};

export type Update6Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * The tag does not exist
   */
  404: unknown;
  /**
   * Any name is used by an existing tag
   */
  409: unknown;
  /**
   * Implications or suggestions create a cyclic dependency
   */
  422: unknown;
};

export type Update6Responses = {
  200: TagInfo;
};

export type Update6Response = Update6Responses[keyof Update6Responses];

export type List7Data = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
    /**
     * Starting position in the result set
     */
    offset?: number | null;
    /**
     * Maximum number of results to return
     */
    limit: number;
  };
  url: '/tags';
};

export type List7Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List7Responses = {
  200: PagedResponseTagInfo;
};

export type List7Response = List7Responses[keyof List7Responses];

export type Create6Data = {
  body: TagCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/tags';
};

export type Create6Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Any name is used by an existing tag
   */
  409: unknown;
  /**
   * Implications or suggestions create a cyclic dependency
   */
  422: unknown;
};

export type Create6Responses = {
  200: TagInfo;
};

export type Create6Response = Create6Responses[keyof Create6Responses];

export type UploadData = {
  body: UploadBody;
  path?: never;
  query?: never;
  url: '/uploads';
};

export type UploadErrors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type UploadResponses = {
  200: UploadResponse;
};

export type UploadResponse2 = UploadResponses[keyof UploadResponses];

export type Create7Data = {
  body: UserTokenCreateBody;
  path: {
    /**
     * Username
     */
    username: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/user-token/{username}';
};

export type Create7Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * User does not exist
   */
  404: unknown;
};

export type Create7Responses = {
  200: UserTokenInfo;
};

export type Create7Response = Create7Responses[keyof Create7Responses];

export type Delete7Data = {
  body: {
    [key: string]: unknown;
  };
  path: {
    /**
     * Username
     */
    username: string;
    /**
     * User token UUID
     */
    token: string;
  };
  query?: never;
  url: '/user-token/{username}/{token}';
};

export type Delete7Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * Token does not exist
   */
  404: unknown;
};

export type Delete7Responses = {
  200: {
    [key: string]: unknown;
  };
};

export type Delete7Response = Delete7Responses[keyof Delete7Responses];

export type Update7Data = {
  body: UserTokenUpdateBody;
  path: {
    /**
     * Username
     */
    username: string;
    /**
     * User token UUID
     */
    token: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/user-token/{username}/{token}';
};

export type Update7Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * User token does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type Update7Responses = {
  200: UserTokenInfo;
};

export type Update7Response = Update7Responses[keyof Update7Responses];

export type List8Data = {
  body?: never;
  path: {
    /**
     * Username
     */
    username: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/user-tokens/{username}';
};

export type List8Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * User does not exist
   */
  404: unknown;
};

export type List8Responses = {
  200: UnpagedResponseUserTokenInfo;
};

export type List8Response = List8Responses[keyof List8Responses];

export type Delete8Data = {
  body: DeleteBody;
  path: {
    /**
     * Username
     */
    name: string;
  };
  query?: never;
  url: '/user/{name}';
};

export type Delete8Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * User does not exist
   */
  404: unknown;
  /**
   * Version is outdated
   */
  409: unknown;
};

export type Delete8Responses = {
  200: {
    [key: string]: unknown;
  };
};

export type Delete8Response = Delete8Responses[keyof Delete8Responses];

export type Get8Data = {
  body?: never;
  path: {
    /**
     * Username
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/user/{name}';
};

export type Get8Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
  /**
   * User does not exist
   */
  404: unknown;
};

export type Get8Responses = {
  200: UserInfo;
};

export type Get8Response = Get8Responses[keyof Get8Responses];

export type Update8Data = {
  body: UserUpdateBody;
  path: {
    /**
     * Username
     */
    name: string;
  };
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/user/{name}';
};

export type Update8Errors = {
  /**
   * Avatar is missing for manual avatar style
   */
  400: unknown;
  /**
   * Trying to set rank higher than own rank
   */
  403: unknown;
  /**
   * User does not exist
   */
  404: unknown;
  /**
   * A user with new name already exists
   */
  409: unknown;
  /**
   * Rank is invalid
   */
  422: unknown;
};

export type Update8Responses = {
  200: UserInfo;
};

export type Update8Response = Update8Responses[keyof Update8Responses];

export type List9Data = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
    /**
     * Starting position in the result set
     */
    offset?: number | null;
    /**
     * Maximum number of results to return
     */
    limit: number;
  };
  url: '/users';
};

export type List9Errors = {
  /**
   * Privileges are too low
   */
  403: unknown;
};

export type List9Responses = {
  200: PagedResponseUserInfo;
};

export type List9Response = List9Responses[keyof List9Responses];

export type Create8Data = {
  body: UserCreateBody;
  path?: never;
  query?: {
    /**
     * Query search string
     */
    query?: string | null;
    /**
     * Comma-separated list of fields to include in the response. See [field selection](#Field-Selection) for details.
     */
    fields?: string | null;
  };
  url: '/users';
};

export type Create8Errors = {
  /**
   * Avatar is missing for manual avatar style
   */
  400: unknown;
  /**
   * Trying to set rank higher than own rank
   */
  403: unknown;
  /**
   * A user with such name already exists
   */
  409: unknown;
  /**
   * Rank is invalid
   */
  422: unknown;
};

export type Create8Responses = {
  200: UserInfo;
};

export type Create8Response = Create8Responses[keyof Create8Responses];
