[package]
name = "oxibooru_server"
version = "0.8.1"
license = "GPL-3.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
axum = { version = "0.8.4", features = ["multipart"] }
base64 = "0.22.1"
blake3 = { version = "1.5.5", features = ["traits-preview"] }
compact_str = { version = "0.9.0", features = ["serde"] }
config = { version = "0.15.18", default-features = false, features = ["toml"] }
diesel = { version = "2.3.10", features = ["postgres", "r2d2", "time", "uuid", "serde_json",
                                          "i-implement-a-third-party-backend-and-opt-into-breaking-changes"] }
diesel_migrations = { version = "2.3.0", features = ["postgres"] }
dotenvy = { version = "0.15.7", optional = true }
ffmpeg-sidecar = { version = "2.5.0", default-features = false }
flate2 = "1.0.35"
futures-core = "0.3.33"
hex = "0.4.3"
hmac = "0.13.0"
image = { version = "0.25.5", default-features = false, features = ["bmp", "gif", "jpeg", "png", "webp", "rayon"] }
jxl = "0.6.0"
infer = "0.22.0"
lettre = { version = "0.11.12", features = ["serde"] }
md5 = "0.7.0"
mime = "0.3.17"
num-traits = "0.2.19"
openssl-sys = { version = "0.9.114", features = ["vendored"] }
percent-encoding = "2.3.1"
pq-sys = { version = "0.7.5", features = ["bundled"] }
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version ="0.12.12", features = ["json", "stream"] }
rustyline = { version = "17.0.2", default-features = false, features = ["signal-hook"] }
serde = { version = "1.0.217", features = ["derive", "rc"] }
sha2 = "0.10"
serde_json = "1.0.138"
serde_repr = "0.1.19"
serde_with = "3.21.0"
server-macros = { path = "macros" }
signal-hook = "0.3.18"
strum = { version = "0.27.0", features = ["derive"] }
swf = "0.2.2"
thiserror = "2.0.11"
time = { version = "0.3.47", features = ["serde-human-readable"] }
tokio = { version = "1.43.0", features = ["fs", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6.6", features = ["trace", "timeout", "normalize-path"] }
tower-layer = "0.3.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
url = { version = "2.5.4", features = ["serde"] }
utoipa = { version = "5.4.0", features = ["axum_extras", "time", "url", "uuid"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }
uuid = { version = "1.13.1", features = ["v4", "serde"] }
walkdir = "2.5.0"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[patch.crates-io]
infer = { git = "https://github.com/liamw1/infer" }

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1.48"

[dev-dependencies]
axum-test = "17.3.0"
serial_test = "3.2.0"

[features]
default = ["load_env"]
load_env = ["dep:dotenvy"]

[profile.release] 
strip = true

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
too_many_arguments = "allow"        # Gives warnings on derives
cast_possible_truncation = "allow"  # Gives warnings for integer casts in const context
cast_possible_wrap = "allow"        # Gives warnings for integer casts in const context
option_option = "allow"             # Option<Option<T>> is convenient for deserializing optional nullable JSON fields
float_cmp = "allow"                 # Buggy: Fires when using assert_eq! to compare to 0.0
unreadable_literal = "allow"        # Don't like how separated form looks for decimal literals
too_many_lines = "allow"            # Too subjective
